### ISSUE TITLE
[webpack integration] Options to include or time node_modules do not seem to be working

### ISSUE THREAD

**Issue by bbugh** [toomuchdesign/babel-timing#53]
## 🐛 Bug Report

Hi 👋 thanks for this library. We're working on optimizing some of our built time node_modules package usage. Our app code itself is probably fine, but our vendor pack is taking quite a while to build. 
## To Reproduce

We've been trying all of the different combinations of options for babel-timing, and none of them seem to include `node_modules` in the timing calculations. 

1. The default of `exclude` is `['**/node_modules/**']`. If we provide that as an empty array, node_modules still appears to be excluded. 
2. `followImports` seems to imply that it would look into `node_modules` also
3. `aggregateBy` just swaps between babel plugins and project files
4. `expandPackages` also seems to imply that it would show node_modules, but it doesn't

I would show you my configuration, but it's just a bunch of different variations of the above options. For example:

```javascript
  new BabelTimingPlugin({
    exclude: [''],
    followImports: true,
    expandPackages: true
  })
```

We are using the webpack plugin.

## Expected behavior

Ideally we could get the timing by `node_module` path (like `node_modules/some_package`). Or we could at least get it by file in the JSON output.

Thanks for reading!

**Comment by toomuchdesign** [comment]
Hi @bbugh,
reading through the [tests](https://github.com/toomuchdesign/babel-timing/blob/9ffdc9e7d3f05d92ff6db9fb42772569b3e756f6/src/__tests__/babelTiming.test.js#L75), it seems that **empty strings** are not valid `exclude` entries. For some reason they break tests. Would you mind trying again with an **empty array**?

**Comment by bbugh** [comment]
@toomuchdesign Thanks for the reply. That is actually the first thing that I tried!

```javascript
new BabelTimingPlugin({exclude: []})
```

Are `node_modules` timing supposed to be in the output by default or can they be added with a configuration? I wasn't clear if what I was trying to do was actually supported.

**Comment by toomuchdesign** [comment]
Right, `BabelTimingPlugin` accepts only `output` and `outputPath` options.

Once you've configured it, the plugin is supposed to record anything transpiled by your local webpack process. Therefore there is nothing to include/exclude here.

Dumb question 1: is `babel-loader` in your webpack configuration actually set up to transpile packages from `node_modules`?

Question 2: how do you run webpack?

These are the [tests for webpack plugin](https://github.com/toomuchdesign/babel-timing/tree/master/webpack/__tests__), in case you're looking for a reference.
