### ISSUE TITLE
Unable to install package with npm: `dist/src/cli.js` not found

### ISSUE THREAD

**Issue by malthejorgensen** [toomuchdesign/babel-timing#63]
## 🐛 Bug Report

When running `npm i babel-timing -D` as stated in the README.md, I get the following error message:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /<path>/<to>/project>/node_modules/babel-timing/dist/src/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/<path>/<to>/project>/node_modules/babel-timing/dist/src/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /<user>/.npm/_logs/2020-12-20T19_22_22_838Z-debug.log
```

A similar error message can be seen if you go to https://unpkg.com/babel-timing@0.9.0.

Installing with `yarn add babel-timing -D` seems to work.

## Run `npx envinfo --preset jest`

Paste the results here:

```bash
  System:
    OS: macOS
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 14.14.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
```

**Comment by toomuchdesign** [comment]
Hi @malthejorgensen, thanks for reporting. It turned out `dist` folder's content was not included in the tarball because of TS copying `package.json` file in it. 🤯 

I'll publish a fix asap.

**Comment by toomuchdesign** [comment]
The issue was autoclosed :) @malthejorgensen, did v0.9.1 solve the problem?

**Comment by malthejorgensen** [comment]
Yup – `npm install babel-timing@0.9.1` works!
